services:
  development-rwsols:
    build: ./build
    image: tdeppner/remote-wake-sleep-on-lan-docker
    container_name: development-rwsols
    restart: unless-stopped
    network_mode: host
    environment:
      - APACHE2_PORT=9898
      - PASSPHRASE=MyPassword
      - RWSOLS_COMPUTER_NAME="Pc1","Pc2"
      - RWSOLS_COMPUTER_MAC="ff:ff:00:00:ff:ff","XX:XX:XX:XX:XX:XX"
      - RWSOLS_COMPUTER_IP="192.168.1.45","192.168.1.50"

### ENV-file presets ###
# Europe/Berlin
# 996
